=== tria-db/rxs2tria/inst/extdata/json_schema/20260402_tria_shinyext_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "extended_shiny_thema",
    "title": "TRIA metadata schema",
    "description": "Extended Schema for .. TODO: adapt properly for roxas ai",
    "type": "object",
    "properties":
    {
        "dataset": { "$ref": "base_schema/20260313_tria_ds_data_schema.json" },
        "authors": { "$ref": "20251007_tria_author_ext_schema.json" },
        "funding": { "$ref": "20251007_tria_funding_ext_schema.json" },
        "related": { "$ref": "20251007_tria_relresource_ext_schema.json" },
        "resources": {"$ref": "base_schema/20260331_tria_resource_data_schema.json" },
        "sites": { "$ref": "20251007_tria_site_ext_schema.json" },
        "trees": { "$ref": "20251007_tria_tree_ext_schema.json" },
        "woodpieces": { "$ref": "20251007_tria_woodpiece_ext_schema.json" },
        "slides": { "$ref": "20251007_tria_slide_ext_schema.json" },
        "images": { 
          "anyOf": [
            { "$ref": "20260313_tria_roxas_ext_schema.json" },
            { "$ref": "base_schema/20260313_tria_roxasai_data_schema.json" }
          ]
        }
    },
    "required":
    [
        "dataset",
        "authors",
        "funding",
        "sites",
        "trees",
        "woodpieces",
        "slides",
        "images"
    ],
    "additionalProperties": true
}

=== tria-db/rxs2tria/test_meta.json
{
  "dataset": {},
  "authors": {},
  "funding": {},
  "related": {},
  "resources": {},
  "sites": {},
  "trees": {},
  "woodpieces": {},
  "slides": {},
  "images": [
    {
      "image_label": "POG_PISY_02_B_1_1",
      "slide_label": "POG_PISY_02_B_1",
      "woodpiece_label": "POG_PISY_02_B",
      "tree_label": "POG_PISY_02",
      "species_code": "PISY",
      "site_label": "POG",
      "spatial_resolution": 2.2675,
      "meas_geometry": "linear",
      "org_img_name": "POG_PISY_02B_1_1",
      "img_filetype": "JPEG",
      "img_size": 23845088,
      "img_width": 5001,
      "img_height": 31230,
      "img_created_at": null,
      "img_software": null,
      "software": "roxas",
      "sw_version": "3.0.608",
      "rxs_created_at": "2021-04-09T15:03:00",
      "outmost_year": 2018,
      "fname_image": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_1_1.jpg",
      "fname_cells": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_1_1_Output_Cells.txt",
      "fname_rings": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_1_1_Output_Rings.txt",
      "fname_settings": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_1_1_ROXAS_Settings.txt",
      "configuration_file": "Pinus_sylvestris_RNF_Alberto_2.267574",
      "origin_calibrated_x": 2500,
      "origin_calibrated_y": -150000,
      "circ_lower_limit": 179,
      "circ_upper_limit": 181,
      "min_cell_area": 5,
      "max_cell_area": 2500,
      "cluster_dbl_cwt_threshold": 0,
      "max_cwtrad_s": 10,
      "max_cwtrad_l": 4,
      "relwidth_cwt_window": 0.75,
      "maxrel_opp_cwt": 1.5,
      "max_cwttan_s": 10,
      "max_cwttan_l": 4,
      "rw_reference_file": "_RW_Series.rwl"
    },
    {
      "image_label": "POG_PISY_02_B_1_2",
      "slide_label": "POG_PISY_02_B_1",
      "woodpiece_label": "POG_PISY_02_B",
      "tree_label": "POG_PISY_02",
      "species_code": "PISY",
      "site_label": "POG",
      "spatial_resolution": 2.2675,
      "meas_geometry": "linear",
      "org_img_name": "POG_PISY_02B_1_2",
      "img_filetype": "JPEG",
      "img_size": 24110909,
      "img_width": 5000,
      "img_height": 30824,
      "img_created_at": null,
      "img_software": null,
      "software": "roxas",
      "sw_version": "3.0.608",
      "rxs_created_at": "2021-10-11T20:00:00",
      "outmost_year": 2010,
      "fname_image": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_1_2.jpg",
      "fname_cells": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_1_2_Output_Cells.txt",
      "fname_rings": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_1_2_Output_Rings.txt",
      "fname_settings": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_1_2_ROXAS_Settings.txt",
      "configuration_file": "Pinus_sylvestris_RNF_Alberto_2.57102",
      "origin_calibrated_x": 2500,
      "origin_calibrated_y": -150000,
      "circ_lower_limit": 179,
      "circ_upper_limit": 181,
      "min_cell_area": 5,
      "max_cell_area": 2500,
      "cluster_dbl_cwt_threshold": 0,
      "max_cwtrad_s": 10,
      "max_cwtrad_l": 4,
      "relwidth_cwt_window": 0.75,
      "maxrel_opp_cwt": 1.5,
      "max_cwttan_s": 10,
      "max_cwttan_l": 4,
      "rw_reference_file": "_RW_Series.rwl"
    },
    {
      "image_label": "POG_PISY_02_B_1_3",
      "slide_label": "POG_PISY_02_B_1",
      "woodpiece_label": "POG_PISY_02_B",
      "tree_label": "POG_PISY_02",
      "species_code": "PISY",
      "site_label": "POG",
      "spatial_resolution": 2.2675,
      "meas_geometry": "linear",
      "org_img_name": "POG_PISY_02B_1_3",
      "img_filetype": "JPEG",
      "img_size": 9917677,
      "img_width": 5001,
      "img_height": 14886,
      "img_created_at": null,
      "img_software": null,
      "software": "roxas",
      "sw_version": "3.0.608",
      "rxs_created_at": "2021-04-09T15:06:00",
      "outmost_year": 2003,
      "fname_image": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_1_3.jpg",
      "fname_cells": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_1_3_Output_Cells.txt",
      "fname_rings": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_1_3_Output_Rings.txt",
      "fname_settings": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_1_3_ROXAS_Settings.txt",
      "configuration_file": "Pinus_sylvestris_RNF_Alberto_2.267574",
      "origin_calibrated_x": 2500,
      "origin_calibrated_y": -150000,
      "circ_lower_limit": 179,
      "circ_upper_limit": 181,
      "min_cell_area": 5,
      "max_cell_area": 2500,
      "cluster_dbl_cwt_threshold": 0,
      "max_cwtrad_s": 10,
      "max_cwtrad_l": 4,
      "relwidth_cwt_window": 0.75,
      "maxrel_opp_cwt": 1.5,
      "max_cwttan_s": 10,
      "max_cwttan_l": 4,
      "rw_reference_file": "_RW_Series.rwl"
    },
    {
      "image_label": "POG_PISY_02_B_2_1",
      "slide_label": "POG_PISY_02_B_2",
      "woodpiece_label": "POG_PISY_02_B",
      "tree_label": "POG_PISY_02",
      "species_code": "PISY",
      "site_label": "POG",
      "spatial_resolution": 2.2675,
      "meas_geometry": "linear",
      "org_img_name": "POG_PISY_02B_2_1",
      "img_filetype": "JPEG",
      "img_size": 36561587,
      "img_width": 5001,
      "img_height": 31446,
      "img_created_at": null,
      "img_software": null,
      "software": "roxas",
      "sw_version": "3.0.608",
      "rxs_created_at": "2021-10-11T18:45:00",
      "outmost_year": 2001,
      "fname_image": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_2_1.jpg",
      "fname_cells": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_2_1_Output_Cells.txt",
      "fname_rings": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_2_1_Output_Rings.txt",
      "fname_settings": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_2_1_ROXAS_Settings.txt",
      "configuration_file": "Pinus_sylvestris_RNF_Alberto_2.267574",
      "origin_calibrated_x": 2500,
      "origin_calibrated_y": -150000,
      "circ_lower_limit": 179,
      "circ_upper_limit": 181,
      "min_cell_area": 5,
      "max_cell_area": 2500,
      "cluster_dbl_cwt_threshold": 0,
      "max_cwtrad_s": 10,
      "max_cwtrad_l": 4,
      "relwidth_cwt_window": 0.75,
      "maxrel_opp_cwt": 1.5,
      "max_cwttan_s": 10,
      "max_cwttan_l": 4,
      "rw_reference_file": "_RW_Series.rwl"
    },
    {
      "image_label": "POG_PISY_02_B_2_2",
      "slide_label": "POG_PISY_02_B_2",
      "woodpiece_label": "POG_PISY_02_B",
      "tree_label": "POG_PISY_02",
      "species_code": "PISY",
      "site_label": "POG",
      "spatial_resolution": 2.2675,
      "meas_geometry": "linear",
      "org_img_name": "POG_PISY_02B_2_2",
      "img_filetype": "JPEG",
      "img_size": 25138482,
      "img_width": 5001,
      "img_height": 30076,
      "img_created_at": null,
      "img_software": null,
      "software": "roxas",
      "sw_version": "3.0.608",
      "rxs_created_at": "2021-10-11T18:53:00",
      "outmost_year": 1990,
      "fname_image": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_2_2.jpg",
      "fname_cells": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_2_2_Output_Cells.txt",
      "fname_rings": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_2_2_Output_Rings.txt",
      "fname_settings": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_2_2_ROXAS_Settings.txt",
      "configuration_file": "Pinus_sylvestris_RNF_Alberto_2.267574",
      "origin_calibrated_x": 2500,
      "origin_calibrated_y": -150000,
      "circ_lower_limit": 179,
      "circ_upper_limit": 181,
      "min_cell_area": 5,
      "max_cell_area": 2500,
      "cluster_dbl_cwt_threshold": 0,
      "max_cwtrad_s": 10,
      "max_cwtrad_l": 4,
      "relwidth_cwt_window": 0.75,
      "maxrel_opp_cwt": 1.5,
      "max_cwttan_s": 10,
      "max_cwttan_l": 4,
      "rw_reference_file": "_RW_Series.rwl"
    },
    {
      "image_label": "POG_PISY_02_B_2_3",
      "slide_label": "POG_PISY_02_B_2",
      "woodpiece_label": "POG_PISY_02_B",
      "tree_label": "POG_PISY_02",
      "species_code": "PISY",
      "site_label": "POG",
      "spatial_resolution": 2.2675,
      "meas_geometry": "linear",
      "org_img_name": "POG_PISY_02B_2_3",
      "img_filetype": "JPEG",
      "img_size": 15011751,
      "img_width": 5000,
      "img_height": 20846,
      "img_created_at": null,
      "img_software": null,
      "software": "roxas",
      "sw_version": "3.0.608",
      "rxs_created_at": "2021-10-11T19:03:00",
      "outmost_year": 1982,
      "fname_image": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_2_3.jpg",
      "fname_cells": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_2_3_Output_Cells.txt",
      "fname_rings": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_2_3_Output_Rings.txt",
      "fname_settings": "/Users/maranaegelin/Documents/QWAdata/example_dataset/roxas_out/POG/POG_02B/POG_PISY_02B_2_3_ROXAS_Settings.txt",
      "configuration_file": "Pinus_sylvestris_RNF_Alberto_2.267574",
      "origin_calibrated_x": 2500,
      "origin_calibrated_y": -150000,
      "circ_lower_limit": 179,
      "circ_upper_limit": 181,
      "min_cell_area": 5,
      "max_cell_area": 2500,
